from sqlalchemy.orm import mapper

from core.models.product_periodicity_model import ProductPeriodicityModel
from infrastructure.data.product_periodicity_entity import product_periodicity_table

mapper(ProductPeriodicityModel, product_periodicity_table)