CONNECTION:
  USER: root
  PASSWORD: ricardu123_mysql
  HOST: 127.0.0.1
  PORT: 3306
  DATABASE: apigest

LOGGER:
  version: 1
  disable_existing_loggers: true
  formatters:
    simple:
      format: '%(name)s - %(levelname)s - %(message)s'
    console_formatter:
      format: '[%(asctime)-10s] | %(name)s | %(levelname)-7s | %(message)s'
    file_formatter:
      format: '[%(asctime)-10s] | %(name)s | %(levelname)-7s | %(message)s'
      datefmt: '%d-%m-%Y %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: console_formatter
      stream: ext://sys.stdout
    dev_file:
      class: logging.FileHandler
      level: INFO
      filename: dev_logs.log
      formatter: file_formatter
    test_file:
      class: logging.FileHandler
      level: DEBUG
      filename: test_logs.log
      formatter: file_formatter
  loggers:
    dev:
      handlers: [console, dev_file]
    test:
      handlers: [console, test_file]
  root:
    level: DEBUG